const fs = require("fs");
const path = require("path");

// These should match the names of your Secrets / Env Variables
const config = {
	apiKey: process.env.FIREBASE_API_KEY,
	authDomain: process.env.FIREBASE_AUTH_DOMAIN,
	projectId: process.env.FIREBASE_PROJECT_ID,
	storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
	messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
	appId: process.env.FIREBASE_APP_ID
};

const fileContent = `// Generated by build-config.js
const firebaseConfig = {
	apiKey: "${config.apiKey || 'MISSING_ENV_VAR'}",
	authDomain: "${config.authDomain || 'MISSING_ENV_VAR'}",
	projectId: "${config.projectId || 'MISSING_ENV_VAR'}",
	storageBucket: "${config.storageBucket || 'MISSING_ENV_VAR'}",
	messagingSenderId: "${config.messagingSenderId || 'MISSING_ENV_VAR'}",
	appId: "${config.appId || 'MISSING_ENV_VAR'}"
};

export default firebaseConfig;
`;

const outputPath = path.join(__dirname, "src", "apis", "config.js");

try {
	fs.writeFileSync(outputPath, fileContent);
	console.log("good");
} catch (error) {
	console.error("fuck:", error);
	process.exit(1);
}
