const fs = require("fs");
const path = require("path");

// Configuration from Env Vars
const config = {
	apiKey: process.env.FIREBASE_API_KEY,
	authDomain: process.env.FIREBASE_AUTH_DOMAIN,
	projectId: process.env.FIREBASE_PROJECT_ID,
	storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
	messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
	appId: process.env.FIREBASE_APP_ID
};

const distDir = path.join(__dirname, "dist");
const srcDir = path.join(__dirname, "src");

// Function to copy directory recursively
function copyDir(source, destination) {
	if (!fs.existsSync(destination)) {
		fs.mkdirSync(destination, { recursive: true });
	}

	// Check if source exists
	if (!fs.existsSync(source)) {
		return;
	}

	const entries = fs.readdirSync(source, { withFileTypes: true });

	for (const entry of entries) {
		const srcPath = path.join(source, entry.name);
		const destPath = path.join(destination, entry.name);

		if (entry.isDirectory()) {
			copyDir(srcPath, destPath);
		} else {
			fs.copyFileSync(srcPath, destPath);
		}
	}
}

try {
	console.log("Starting Build...");

	// 1. Clean/Create dist folder
	if (fs.existsSync(distDir)) {
		fs.rmSync(distDir, { recursive: true, force: true });
	}
	fs.mkdirSync(distDir);

	// 2. Copy index.html
	if (fs.existsSync(path.join(__dirname, "index.html"))) {
		fs.copyFileSync(path.join(__dirname, "index.html"), path.join(distDir, "index.html"));
	}

	// 3. Copy src folder
	copyDir(srcDir, path.join(distDir, "src"));

	// 4. Generate config.js in dist/src/apis/config.js
	const configFileContent = `// Generated by build-config.js
const firebaseConfig = {
	apiKey: "${config.apiKey || 'MISSING_ENV_VAR'}",
	authDomain: "${config.authDomain || 'MISSING_ENV_VAR'}",
	projectId: "${config.projectId || 'MISSING_ENV_VAR'}",
	storageBucket: "${config.storageBucket || 'MISSING_ENV_VAR'}",
	messagingSenderId: "${config.messagingSenderId || 'MISSING_ENV_VAR'}",
	appId: "${config.appId || 'MISSING_ENV_VAR'}"
};

export default firebaseConfig;
`;

	const configPath = path.join(distDir, "src", "apis", "config.js");
	fs.writeFileSync(configPath, configFileContent);

	console.log("Build success. Output directory: /dist");

} catch (error) {
	console.error("Build fucked:", error);
	process.exit(1);
}
